### ISSUE TITLE
NegativeArraySizeException

### ISSUE THREAD

**Issue by tresf** [BlackOverlord666/mslinks#4]
I believe I've found a bug with `new ShellLink("foo.lnk")`

What works:
 * Link created with mslinks on Windows 10, Windows XP
 * Link created with NSIS `CreateShortCut <link> <exe> <params> <icon> <index>` on Windows 10

What doesn't work:
 * Link created with NSIS [`CreateShortCut <link> <exe> <icon> <index>`](http://nsis.sourceforge.net/Reference/CreateShortCut) on Windows XP.
  * Note, the offending file works fine with the OS (Launcher works, Properties open, etc).
  
I've attached some sample `lnk` files for examination [here](https://github.com/BlackOverlord666/mslinks/files/477943/issue4.zip).

For now, [the workaround](https://github.com/tresf/tray/commit/5b97eb3ccd18d9364856dabaa7d5985516661e6f) is to catch the exception on Windows XP and optionally rewrite the icon using `mslinks` when the exception occurs.

Backtrace:
```
java.lang.NegativeArraySizeException
        at io.ByteReader.readUnicodeString(ByteReader.java:161)
        at mslinks.data.ItemID.<init>(ItemID.java:74)
        at mslinks.LinkTargetIDList.<init>(LinkTargetIDList.java:45)
        at mslinks.ShellLink.<init>(ShellLink.java:90)
        at mslinks.ShellLink.<init>(ShellLink.java:82)
        at mslinks.ShellLink.<init>(ShellLink.java:77)
        at mslinks.ShellLink.<init>(ShellLink.java:69)
        at qz.deploy.WindowsDeploy.hasStartupShortcut(Unknown Source)
        at qz.deploy.DeployUtilities.hasShortcut(Unknown Source)
        at qz.deploy.DeployUtilities.createShortcut(Unknown Source)
        at qz.common.TrayManager.shortcutToggle(Unknown Source)
        at qz.common.TrayManager.lambda$new$2(Unknown Source)
        at javax.swing.AbstractButton.fireActionPerformed(Unknown Source)
        at javax.swing.AbstractButton$Handler.actionPerformed(Unknown Source)
        at javax.swing.DefaultButtonModel.fireActionPerformed(Unknown Source)
        at javax.swing.JToggleButton$ToggleButtonModel.setPressed(Unknown Source)
        at javax.swing.AbstractButton.doClick(Unknown Source)
        at javax.swing.plaf.basic.BasicMenuItemUI.doClick(Unknown Source)
        at javax.swing.plaf.basic.BasicMenuItemUI$Handler.mouseReleased(Unknown Source)
        at java.awt.Component.processMouseEvent(Unknown Source)
        at javax.swing.JComponent.processMouseEvent(Unknown Source)
        at java.awt.Component.processEvent(Unknown Source)
        at java.awt.Container.processEvent(Unknown Source)
        at java.awt.Component.dispatchEventImpl(Unknown Source)
        at java.awt.Container.dispatchEventImpl(Unknown Source)
        at java.awt.Component.dispatchEvent(Unknown Source)
        at java.awt.LightweightDispatcher.retargetMouseEvent(Unknown Source)
        at java.awt.LightweightDispatcher.processMouseEvent(Unknown Source)
        at java.awt.LightweightDispatcher.dispatchEvent(Unknown Source)
        at java.awt.Container.dispatchEventImpl(Unknown Source)
        at java.awt.Window.dispatchEventImpl(Unknown Source)
        at java.awt.Component.dispatchEvent(Unknown Source)
        at java.awt.EventQueue.dispatchEventImpl(Unknown Source)
        at java.awt.EventQueue.access$500(Unknown Source)
        at java.awt.EventQueue$3.run(Unknown Source)
        at java.awt.EventQueue$3.run(Unknown Source)
        at java.security.AccessController.doPrivileged(Native Method)
        at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(Unknown Source)
        at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(Unknown Source)
        at java.awt.EventQueue$4.run(Unknown Source)
        at java.awt.EventQueue$4.run(Unknown Source)
        at java.security.AccessController.doPrivileged(Native Method)
        at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(Unknown Source)
        at java.awt.EventQueue.dispatchEvent(Unknown Source)
        at java.awt.EventDispatchThread.pumpOneEventForFilters(Unknown Source)
        at java.awt.EventDispatchThread.pumpEventsForFilter(Unknown Source)
        at java.awt.EventDispatchThread.pumpEventsForHierarchy(Unknown Source)
        at java.awt.EventDispatchThread.pumpEvents(Unknown Source)
        at java.awt.EventDispatchThread.pumpEvents(Unknown Source)
        at java.awt.EventDispatchThread.run(Unknown Source)
```

**Comment by BlackOverlord666** [comment]
Yes, it seems LinkTargetIDList section (which is very poorly documented and implemented mostly through reverse enginering) sometimes is read wrong. I will try to take a look at issue tomorrow. Can you provide a sample script for NSIS, that creates shortcuts?

PS Why do your lnk files actually have `.dat` extension?

**Comment by tresf** [comment]
> Can you provide a sample script for NSIS that creates shortcuts?

Absolutely.

```nsi
; Run silently in user-space
RequestExecutionLevel user
SilentInstall silent
AutoCloseWindow true
ShowInstDetails nevershow

; Create installer stub
Section ""
  CreateShortcut "$DESKTOP\Issue41.lnk" "$WINDIR\system32\rundll32.exe" \
        "" "$WINDIR\system32\SHELL32.dll" 0
SectionEnd
```

> PS Why do your lnk files actually have .dat extension?

Out of courtesy to GitHub and any users downloading the attachments as `.lnk` files are executables and often blocked by email|upload|av|etc.

**Comment by BlackOverlord666** [comment]
Finally, I fixed that. Now it should correctly work with shortcuts created on win xp, vista, 7, 8, 10. I've also added support for older windows versions (tested on 98 and 2000).
